### ISSUE TITLE
1st CRAN release plan

### ISSUE THREAD

**Issue by eblondel** [eblondel/geoflow#234]
- [x] #40 Set of Integration tests ready (to be further enriched later)
- [x] #249 Apply strict R6 class documentation with roxygen2
- [x] Need 'd4storagehub4R' package to be published on CRAN (https://github.com/eblondel/d4storagehub4R)
- [x] Need 'thredds' package to be published on CRAN (https://github.com/BigelowLab/thredds/issues/3)
- [x] Need 'atom4R' package to be published on CRAN (https://github.com/eblondel/atom4R/issues/3)
- [x] Need 'geonode4R' package to be published  on CRAN (https://github.com/eblondel/geonode4R/issues/10) 
- [x] Need 'geometa' package update (version `0.8`)
- [x] Review title and description with co-authors @juldebar @wheintz @abennici 
- [x] Submission to CRAN

**Comment by eblondel** [comment]
From CRAN:

Thanks,

Your title is fairly long. Please reduce its length by e.g. omitting the redundant "Tools to" at the start.

Please proofread your DESCRIPTION.
It currently reads:
"Users can also customise their own
  workflows by creating specific actions  but the library comes
  with a set of native actions that have been identified as key
  steps most data managers, in particular actions oriented to
  the publication on the web of metadata  and data resources to
  provide standard discovery and access services."
I think there is missing a word somewhere in there?
Maybe something like:
"Users can also customise their own
  workflows by creating specific actions  but the library comes
  with a set of native actions that have been identified as key
  steps most data managers provide/use/etc... , in particular actions oriented to
  the publication on the web of metadata  and data resources to
  provide standard discovery and access services."

Please always write package names, software names and API (application programming interface) names in single quotes in title and description.
e.g: --> 'OGC', 'DublinCore', 'DataCite', 'DataOne', etc...
Please note that package names are case sensitive.

Please always explain all acronyms in the description text. -> OGC, CSW, EML, CF, etc...

You write information messages to the console that cannot be easily suppressed.
It is more R like to generate objects that can be used to extract the information a user is interested in, and then print() that object. Instead of print()/cat() rather use message()/warning() or if(verbose)cat(..) (or maybe stop()) if you really have to write text to the console. (except for print, summary, interactive functions)
-> R/executeWorkflowJob.R; R/geoflow_data_accessor.R; R/geoflow_logger.R; R/geoflow_utils.R; R/initWorkflow.R

Please ensure that your functions do not write by default or in your examples/vignettes/tests in the user's home filespace (including the package directory and getwd()). This is not allowed by CRAN policies. Please omit any default path in writing functions. In your examples/vignettes/tests you can write to tempdir().

Please make sure that you do not change the user's options, par or working directory. If you really have to do so within functions, please ensure with an *immediate* call of on.exit() that the settings are reset when the function is exited.
e.g.:
...
oldwd <- getwd() # code line i
on.exit(setwd(oldwd)) # code line i+1
...
setwd(...) # somewhere after
...
e.g.: -> R/closeWorkflow.R; R/debugWorkflow.R; R/executeWorkflow.R; R/executeWorkflowJob.R; R/geoflow_entity.R; R/geoflow_software.R; R/initWorkflow.R
If you're not familiar with the function, please check ?on.exit. This function makes it possible to restore options before exiting a function even if the function breaks. Therefore it needs to be called immediately after the option change within a function.

Please fix and resubmit.
