### ISSUE TITLE
New software/action to publish (meta)data on Dataverse

### ISSUE THREAD

**Issue by eblondel** [eblondel/geoflow#35]
Useful links:
* https://datacite.org/
* https://dataverse.org/
* http://guides.dataverse.org/en/latest/api/sword.html
* R package:
    * CRAN: https://cran.r-project.org/package=dataverse
    * Github: https://github.com/iqss/dataverse-client-r
    * Github: https://github.com/eblondel/atom4R

Tasks:
- [x] add ``atom4R`` as embedded geoflow software
- [x] add ``atom4R`` dataverse oriented action
    - [x] manage metadata
    - [x] support for files upload
    - [x] support for publication
